spring:
  application:
    name: gsm-tracker
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: "${ADMIN_PASSWORD:{noop}changeme}"