CREATE TABLE position (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id   BIGINT           NOT NULL REFERENCES device (id),
    lat         DOUBLE PRECISION NOT NULL,
    lon         DOUBLE PRECISION NOT NULL,
    speed       DOUBLE PRECISION,
    accuracy    DOUBLE PRECISION,
    altitude    DOUBLE PRECISION,
    bearing     DOUBLE PRECISION,
    battery     INTEGER,
    recorded_at TIMESTAMPTZ      NOT NULL,
    received_at TIMESTAMPTZ      NOT NULL DEFAULT now(),
    CONSTRAINT uq_position_device_time UNIQUE (device_id, recorded_at)
);

CREATE INDEX ix_position_device_time ON position (device_id, recorded_at DESC);
